export enum MyJourney {
    para1 = "I graduated from Ball State University cum laude in 2018 with a major in Journalism Graphics (graphic design) and a minor in Digital Publishing (printing). During my time at Ball State, I completed two graphic design internships and held two part-time graphic design jobs. Additionally, I took on freelance design work and two community projects with my journalism department peers.",
    para2 = "How does a graphic designer with training in journalism find her way to front-end engineering? My interest in coding was ignited my freshman year when I was introduced to HTML and CSS in an intro to visual communication course. I was immediately fascinated with coding and driven to explore it further. The following year, I took two computer science courses, completing projects with Java and Python. During my junior and senior years, HTML, CSS and JavaScript were the focus of several courses required for the Journalism Graphics major.",
    para3 = "I started my career as a graphic designer while utilizing my journalism training to tackle a variety of marketing tasks. My interest in coding and my aspiration to work in the tech industry lingered. I came to the realization that front-end engineering was truly what I wanted to pursue. I completed Eleven Fifty Academy’s (now known as Blaizing Academy) Web Development program in 2020.",
    para4 = "Since Eleven Fifty, I have held roles as UI/UX Developer, Software Engineer, Angular Developer, and Design Engineer. My passion lies in building user interfaces that are equally beautiful and useful with an emphasis on the user’s needs."
}

export enum skills {
    skillsDesc = "As a versatile engineer who is equally as adept at design as engineering, my skillset spans the entire process of building user interfaces. I like to break my skills into 3 buckets: Ideate, Design and Develop.",
    ideateDesc = "The skills behind my ability to determine solutions to a problem by gathering pertinent information, receiving user/stakeholder input, conducting adequate research, and participation in or ownership of ideation/discovery.",
    designDesc = "The skills behind my ability to bring the results of the discovery/ideation phase to fruition in wireframes, mockups and prototypes in addition to my ability to create or optimize any visuals required for the design.",
    developDesc = "The skills behind my ability to translate a mockup into a fully-functional user interface.",
} 